server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: root
  application:
    name: tb-provider-two

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
mybatis:
  configuration:
    map-underscore-to-camel-case: true
